#!/usr/bin/env python3
"""
Generates programs/sort.jvm : reads n, reads n integers, bubble-sorts them,
and prints them in ascending order.

WHY THIS IS GENERATED RATHER THAN HAND WRITTEN
------------------------------------------------
The instruction subset for this project (per the assignment) has no
"array" opcodes (no newarray/iaload/iastore) -- iload/istore only ever
address a *compile-time constant* local-variable slot. That means a
loop can't do "arr[j]" for a runtime-variable j the way a real sorting
routine would.

The standard trick (and the one used here) is to reserve one fixed local
slot per possible array element (slots 10..10+MAX_N-1), fully UNROLL the
bubble-sort's nested loops at code-generation time (so every "arr[i]"
access is a compile-time-constant local index), and guard each unrolled
block with a runtime comparison against n so it behaves correctly for any
n from 0..MAX_N. The same unrolling trick is used to read exactly n
values and to print exactly n values.

This keeps every instruction 100% within the given subset
(ldc/iload/istore/iadd/isub/imul/idiv/if../goto/read/print) while still
supporting genuinely variable-length input, up to the compile-time cap
MAX_N.

Local variable map:
    0            = n
    10 .. 10+N-1 = the array elements
"""

import argparse

MAX_N_DEFAULT = 10
ARRAY_BASE = 10


def generate(max_n: int) -> str:
    lines = []
    label_counter = [0]

    def emit(s=""):
        lines.append(s)

    def new_label(prefix):
        label_counter[0] += 1
        return f"{prefix}_{label_counter[0]}"

    emit(f"# Auto-generated by tools/generate_sort_program.py  (MAX_N={max_n})")
    emit("# Task (b): read n, read n integers, bubble-sort ascending, print them.")
    emit("#")
    emit("# High-level Java equivalent:")
    emit("#")
    emit("#   int n = read();")
    emit(f"#   int[] a = new int[n];   // n must be <= {max_n} for this simulator")
    emit("#   for (int i = 0; i < n; i++) a[i] = read();")
    emit("#   for (int p = 0; p < n - 1; p++)")
    emit("#       for (int i = 0; i < n - 1 - p; i++)")
    emit("#           if (a[i] > a[i + 1]) { int t = a[i]; a[i] = a[i+1]; a[i+1] = t; }")
    emit("#   for (int i = 0; i < n; i++) print(a[i]);")
    emit("#")
    emit("# Local variable map: 0 = n ; 10.." + str(ARRAY_BASE + max_n - 1) + " = array elements")
    emit()

    # ---- read n ----
    emit("read")
    emit("istore 0")
    emit()

    # ---- read n elements (unrolled + guarded) ----
    emit("# --- read exactly n elements into slots 10..%d ---" % (ARRAY_BASE + max_n - 1))
    for i in range(max_n):
        skip = new_label("SKIP_READ")
        emit(f"ldc {i}")
        emit("iload 0")
        emit(f"if_icmpge {skip}")
        emit("read")
        emit(f"istore {ARRAY_BASE + i}")
        emit(f"{skip}:")
    emit()

    # ---- bubble sort (fully unrolled, guarded by n) ----
    emit("# --- bubble sort, unrolled; each compare/swap guarded by n at runtime ---")
    for p in range(max_n - 1):
        for i in range(max_n - 1 - p):
            skip = new_label("SKIP_CMP")
            a_slot = ARRAY_BASE + i
            b_slot = ARRAY_BASE + i + 1
            emit(f"ldc {i + 1}")
            emit("iload 0")
            emit(f"if_icmpge {skip}          # not enough elements yet")
            emit(f"iload {a_slot}")
            emit(f"iload {b_slot}")
            emit(f"if_icmple {skip}          # already in order, no swap")
            emit(f"iload {a_slot}")
            emit(f"iload {b_slot}")
            emit(f"istore {a_slot}           # a[i] = a[i+1]")
            emit(f"istore {b_slot}           # a[i+1] = old a[i]  (stack used as temp)")
            emit(f"{skip}:")
    emit()

    # ---- print n elements (unrolled + guarded) ----
    emit("# --- print exactly the first n (now-sorted) elements ---")
    for i in range(max_n):
        skip = new_label("SKIP_PRINT")
        emit(f"ldc {i}")
        emit("iload 0")
        emit(f"if_icmpge {skip}")
        emit(f"iload {ARRAY_BASE + i}")
        emit("print")
        emit(f"{skip}:")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-n", type=int, default=MAX_N_DEFAULT,
                         help=f"maximum number of elements supported (default {MAX_N_DEFAULT})")
    parser.add_argument("--out", default="programs/sort.jvm",
                         help="output file path")
    args = parser.parse_args()

    code = generate(args.max_n)
    with open(args.out, "w") as f:
        f.write(code)
    print(f"Wrote {args.out} (max_n={args.max_n}, {code.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
